sudo: enabled
dist: xenial
language: r
warnings_are_errors: true

# Only allow the lintr-bot to comment on the release build (this avoids duplicate comments)
matrix:
  include:
    - r: oldrel
      env: LINTR_COMMENT_BOT=false
    - r: release
    - r: devel
      env: LINTR_COMMENT_BOT=false

# BayesLogit needs the gfortran compiler
apt_packages:
  - gfortran

# Install BayesLogit 0.6 using devtools
before_install:
  - Rscript -e 'install.packages("devtools"); require(devtools); install_version("BayesLogit", version = "0.6")'
  - git clone https://github.com/kasparmartens/PolyaGamma.git && cd PolyaGamma && sed -i 's/M.rtens/Martens/g' DESCRIPTION && Rscript -e "require(devtools); devtools::install('.')"

# Install PolyaGamma using devtools::install_github
r_github_packages:
  - jimhester/lintr

r_packages:
  - covr

after_success:
  - Rscript -e 'covr::codecov()'
