sudo: enabled
language: r
warnings_are_errors: true

# Use Xenial whenever running in Linux (ignored for OS X)
dist: xenial

# Disable lintr-bot comments by default
env:
  - LINTR_COMMENT_BOT=false

# Construct the matrix of OS and R versions
os:
  - linux
  - osx
r:
  - oldrel
  - release
  - devel

# Explicitly enable the lintr-bot for one build (this avoids duplicate comments).
# Travis treats builds with different environment variables as different builds.
# We therefore remove the one we don't want in order to replace it with the one
# we do.
matrix:
  exclude:
    - os: linux
      r: release
      env: LINTR_COMMENT_BOT=false
  include:
    - os: linux
      r: release
      env: LINTR_COMMENT_BOT=true

# macOS 10.12 version
osx_image: xcode9.2

# The lintr R package is slightly behind its Github version but it is fine for
# now. If we have lintr problems in the future, revert to
# ```
# r_github_packages:
#   - jimhester/lintr
# ```

r_packages:
  - covr
  - lintr

after_success:
  - Rscript -e 'covr::codecov()'
