sudo: enabled
language: r
warnings_are_errors: true

# Use Xenial whenever running in Linux (ignored for OS X)
dist: xenial

# Disable lintr-bot comments by default
env:
  - LINTR_COMMENT_BOT=false

# Construct the matrix of OS and R versions
os:
  - linux
  - osx
r:
  - oldrel
  - release
  - devel

# Specify any additional packages that might be needed
addons:
  homebrew:
    packages:
    - libomp
    - llvm

before_install:
  - if [ "${TRAVIS_OS_NAME}" == "osx" ]; then
      mkdir -p ~/.R
      cat <<- EOF > ~/.R/Makevars
        # The following statements are required to use homebrew clang with openmp support
        CC=/usr/local/clang4/bin/clang
        CXX=/usr/local/clang4/bin/clang++
        LDFLAGS=-L/usr/local/clang4/lib
        # End clang4 inclusion statements
  	  EOF
    fi

# Explicitly enable the lintr-bot for one build (this avoids duplicate comments).
# Travis treats builds with different environment variables as different builds.
# We therefore remove the one we don't want in order to replace it with the one
# we do.
matrix:
  exclude:
    - os: linux
      r: release
      env: LINTR_COMMENT_BOT=false
    - os: osx
      r: devel
      env: LINTR_COMMENT_BOT=false
  include:
    - os: linux
      r: release
      env: LINTR_COMMENT_BOT=true

# The lintr R package is slightly behind its Github version but it is fine for
# now. If we have lintr problems in the future, revert to
# ```
# r_github_packages:
#   - jimhester/lintr
# ```

r_packages:
  - covr
  - lintr

after_success:
  - Rscript -e 'covr::codecov()'
