sudo: enabled
language: r
warnings_are_errors: true

# # Only allow the lintr-bot to comment on one build (this avoids duplicate comments)
# matrix:
#   include:
#     # Build for both OSX and Linux
#     - os: linux
#       dist: xenial
#     - os: osx
#       env: LINTR_COMMENT_BOT=false
#     # Build for three R releases
#     - r: oldrel
#       env: LINTR_COMMENT_BOT=false
#     - r: release
#     - r: devel
#       env: LINTR_COMMENT_BOT=false

# Use Xenial whenever running in Linux (ignored for OS X)
dist: xenial

# Disable lintr-bot comments by default
env:
  - LINTR_COMMENT_BOT=false

# Construct the matrix of OS and R versions
os:
  - linux
  - osx
r:
  - oldrel
  - release
  - devel
# Explicitly enable the lintr-bot for one build (this avoids duplicate comments)
matrix:
  include:
    - os: linux
      r: release
      env: LINTR_COMMENT_BOT=true

# matrix:
#   exclude:
#     - rvm: 1.9.3
#       env: DB=mongodb SUITE=all # not 'env: DB=mongodb  SUITE=all' or 'env: SUITE=all DB=mongodb'
#     - rvm: 1.9.3
#       env: DB=mongodb SUITE=compact # not 'env: SUITE=compact DB=mongodb'

# BayesLogit needs the gfortran compiler
apt_packages:
  - gfortran

# Install BayesLogit 0.6 using devtools
before_install:
  - Rscript -e 'install.packages("devtools"); require(devtools); install_version("BayesLogit", version = "0.6")'

# Install PolyaGamma using devtools::install_github
r_github_packages:
  - jimhester/lintr
  - kasparmartens/PolyaGamma

r_packages:
  - covr

after_success:
  - Rscript -e 'covr::codecov()'
