sudo: enabled
language: r
warnings_are_errors: true

# Only allow the lintr-bot to comment on one build (this avoids duplicate comments)
matrix:
  include:
    # Build for both OSX and Linux
    - os: linux
      dist: xenial
    - os: osx
      env: LINTR_COMMENT_BOT=false
    # Build for three R releases
    - r: oldrel
      env: LINTR_COMMENT_BOT=false
    - r: release
    - r: devel
      env: LINTR_COMMENT_BOT=false

# BayesLogit needs the gfortran compiler
apt_packages:
  - gfortran

# Install BayesLogit 0.6 using devtools
before_install:
  - Rscript -e 'install.packages("devtools"); require(devtools); install_version("BayesLogit", version = "0.6")'

# Install PolyaGamma using devtools::install_github
r_github_packages:
  - jimhester/lintr
  - kasparmartens/PolyaGamma

r_packages:
  - covr

after_success:
  - Rscript -e 'covr::codecov()'
