sudo: enabled
dist: xenial
language: r

# Only allow the lintr-bot to comment on the release build (this avoids duplicate comments)
matrix:
  include:
    - r: release
    - r: devel
      env: LINTR_COMMENT_BOT=false

# BayesLogit needs the gfortran compiler
apt_packages:
  - gfortran

# Install BayesLogit 0.6 using devtools
before_install:
  - Rscript -e 'install.packages("devtools"); require(devtools); install_version("BayesLogit", version = "0.6")'

# Install PolyaGamma using devtools::install_github
r_github_packages:
  - jimhester/lintr
  - kasparmartens/PolyaGamma

r_packages:
  - covr
  - lintr

after_script:
  - Rscript -e 'devtools::install(); devtools::test()'
  - R CMD INSTALL $PKG_TARBALL
  - Rscript -e 'lintr::lint_package()'

after_success:
  - Rscript -e 'covr::codecov()'
