sudo: enabled
language: r
warnings_are_errors: true

# Use Xenial whenever running in Linux (ignored for OS X)
dist: xenial

# Disable lintr-bot comments by default
env:
  - LINTR_COMMENT_BOT=false

# Construct the matrix of OS and R versions
os:
  - linux
  - osx
r:
  - oldrel
  - release
  - devel

# Explicitly enable the lintr-bot for one build (this avoids duplicate comments).
# Travis treats builds with different environment variables as different builds.
# We therefore remove the one we don't want in order to replace it with the one
# we do.
matrix:
  exclude:
    - os: linux
      r: release
      env: LINTR_COMMENT_BOT=false
  include:
    - os: linux
      r: release
      env: LINTR_COMMENT_BOT=true

# BayesLogit needs the gfortran compiler
apt_packages:
  - gfortran

# Install BayesLogit 0.6 using devtools
before_install:
  - Rscript -e 'install.packages("devtools"); require(devtools); install_version("BayesLogit", version = "0.6")'

# Install PolyaGamma using devtools::install_github
r_github_packages:
  - jimhester/lintr
  - kasparmartens/PolyaGamma

r_packages:
  - covr

after_success:
  - Rscript -e 'covr::codecov()'
